---
title: "Creating user-specified geographic summaries"
description: >
output: html_vignette
vignette: >
  %\VignetteIndexEntry{Creating user-specified geographic summaries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

```

```{r, load_data, echo=TRUE, eval=TRUE, results = 'hide'}

library(travelSurveyTools)
library(data.table)
library(tigris)

# Load data
data("test_data")
data("variable_list")

states = states()
```

### Creating summaries by geographic variables using hts_summary

`hts_summary` can summarize geographic variables.

```{r, county_income, echo=TRUE, eval=TRUE}

income_county_list = hts_prep_data(
  summarize_var = 'income_detailed',
  summarize_by = 'home_county',
  data = test_data
  )

output = hts_summary(
  prepped_dt = income_county_list$cat,
  summarize_var = 'income_detailed',
  summarize_by = 'home_county'
  )

factorize_df(
  output$summary$unwtd,
  vals_df = value_labels,
  value_label_colname = 'label'
  )
```

### Using join_spatial to join together separate shapefiles

`join_spatial` can link together multiple geographies.

```{r, join_spatial, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}

hh = join_spatial(
    hh,
    dplyr::select(states, home_state = NAME),
    id_col = 'hh_id',
    lon_col = 'home_lon',
    lat_col = 'home_lat',
    largest = TRUE)

hh[, .N, home_state]
```