---
title: "Creating user-specified geographic summaries"
description: >
output: html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

### Creating summaries by geographic variables using hts_summary

`hts_summary` can summarize geographic variables.

```{r, county_income, echo=TRUE, eval=TRUE}

DT = hts_prep_data(summarize_var = 'income_detailed', summarize_by = 'home_county', data = test_data)

output = hts_summary(prepped_dt = DT$cat, summarize_var = 'income_detailed', summarize_by = 'home_county')

factorize_df(output$summary$unwtd, vals_df = value_labels, value_label_colname = 'label')

```

### Using spatial_join to join together separate shapefiles

`spatial_join` can link together multiple geographies.

```{r, spatial_join, echo=TRUE, eval=TRUE}

states = tigris::states()

hh = join_spatial(
    hh,
    dplyr::select(states, home_state = NAME),
    id_col = 'hh_id',
    lon_col = 'home_lon',
    lat_col = 'home_lat',
    largest = TRUE)

hh[, .N, home_state]
```